#!/bin/bash
# Campaign-5 SURFACE generator: the Aito feature's public contract.
# Regenerate the whole file with:  bash tools/gen_surface_aito.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS.
set -u
cd "$(dirname "$0")/.." || exit 1

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/aito\" in r.path]" 2>/dev/null'
R2='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/services/aito_*.py backend/app/services/openrouter.py backend/app/api/routes/aito.py | grep -v "^def _\|^async def _" | sort'
R3='grep -hoE "^class [A-Za-z0-9_]+" backend/app/schemas/aito.py backend/app/models/aito_*.py | sort'
R4='grep -hoE "settings\.[a-z_]+" backend/app/api/routes/aito.py backend/app/services/aito_*.py backend/app/services/openrouter.py | sort -u'
R5='grep -hoE "^export (const|function|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/utils/aito*.ts frontend/src/hooks/useAito*.ts | sort'
R6='grep -rhoE --include="*.ts" --include="*.tsx" "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/components/aito frontend/src/pages/AitoPage.tsx | sort | uniq -c | sed "s/^ *//"'
R7='grep -oE "^  [a-zA-Z][A-Za-z0-9_]*(:|\\()" frontend/src/api/client.ts | grep -iE "aito" | tr -d ":(" | sort -u'

emit() { # emit <heading> <varname>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-5 public contract: the Aito feature (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_aito.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a contract change and fails the iteration.'
echo ''
emit 'Aito HTTP routes (path + methods)'                 "$R1"
emit 'Aito backend public callables'                     "$R2"
emit 'Aito Pydantic schemas + ORM models'                "$R3"
emit 'Settings keys read by Aito backend'                "$R4"
emit 'Aito frontend exported symbols (utils + hooks)'    "$R5"
emit 'Aito component exports (count per symbol name)'    "$R6"
emit 'Aito API client methods'                           "$R7"
