set -u
cd /Users/paultheis/Documents/Code/bambuddy-refactor
R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/aito\" in r.path]" 2>/dev/null'
R2='grep -hoE "^export (const|function|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/utils/aito*.ts frontend/src/hooks/useAito*.ts | sort'
R3='grep -rhoE --include="*.ts" --include="*.tsx" "^export (default function|function|const|type|interface) [A-Za-z0-9_]+" frontend/src/components/aito frontend/src/pages/AitoPage.tsx | sort | uniq -c | sed "s/^ *//"'
R4='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/services/aito_*.py backend/app/api/routes/aito.py | grep -v "^def _\|^async def _" | sort'
R5='grep -hoE "settings\.[a-z_]+" backend/app/api/routes/aito.py backend/app/services/aito_*.py | sort -u'
R6='grep -rhoE --include="*.ts" --include="*.tsx" "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/components/CameraGrid.tsx frontend/src/components/EmbeddedCameraViewer.tsx frontend/src/components/cameraGridLayout.ts frontend/src/components/cameraDefaults.ts frontend/src/components/cameraGrid frontend/src/workers/cameraGridDecoder.worker.ts frontend/src/hooks/useGridStream.ts frontend/src/hooks/useGridReconnect.ts frontend/src/hooks/useCombinedGridStats.ts frontend/src/hooks/useMjpegStream.ts frontend/src/hooks/useWebRTCStream.ts frontend/src/hooks/useStreamReconnect.ts frontend/src/hooks/useCameraControls.ts frontend/src/hooks/useCameraStopHint.ts frontend/src/hooks/useCameraStreamToken.ts | sort | uniq -c | sed "s/^ *//"'
R7='grep -rhoE --include="*.ts" --include="*.tsx" "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/pages/CalculatorPage.tsx frontend/src/pages/CalculatorQuotePage.tsx frontend/src/components/CalculatorSettingsPanels.tsx frontend/src/components/calculator frontend/src/hooks/useCalculatorState.ts frontend/src/utils/pricing.ts frontend/src/utils/calculatorInsights.ts | sort | uniq -c | sed "s/^ *//"'
R8='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"camera\" in r.path]" 2>/dev/null'
R9='grep -rhoE --include="*.ts" "^export (const|function|type|interface) [A-Za-z0-9_]+" frontend/src/utils/clientDraft.ts frontend/src/utils/taskDraft.ts frontend/src/utils/shippingDraft.ts frontend/src/hooks/useNewProjectDraft.ts frontend/src/hooks/useProjectTasks.ts frontend/src/hooks/useOptimisticBoardMutation.ts frontend/src/hooks/useCalculatorState.ts | sort'

{
  echo '# SURFACE.md — campaign-4 public contract: Camera Grid + Aito + Calculator (frozen at setup)'
  echo ''
  echo 'Every section below is generated by the `regen:` command shown above it and is'
  echo 'byte-replayable by re-running that command. Regenerate all of them with'
  echo '`bash tools/gen_surface.sh > SURFACE.md`. ANY diff against this file is a'
  echo 'surface change and fails the iteration.'
  echo ''
  echo '## Aito HTTP routes'
  echo "\`\`\`regen: $R1\`\`\`"
  echo '```'
  eval "$R1"
  echo '```'
  echo ''
  echo '## Aito frontend exported symbols (utils + hooks)'
  echo "\`\`\`regen: $R2\`\`\`"
  echo '```'
  eval "$R2"
  echo '```'
  echo ''
  echo '## Aito frontend component exports (name + count per kind, recursive)'
  echo "\`\`\`regen: $R3\`\`\`"
  echo '```'
  eval "$R3"
  echo '```'
  echo ''
  echo '## Aito backend service/module public functions'
  echo "\`\`\`regen: $R4\`\`\`"
  echo '```'
  eval "$R4"
  echo '```'
  echo ''
  echo '## Settings/env keys referenced by aito modules'
  echo "\`\`\`regen: $R5\`\`\`"
  echo '```'
  eval "$R5"
  echo '```'
  echo ''
  echo '## Camera Grid frontend exports (components + worker + stream hooks)'
  echo "\`\`\`regen: $R6\`\`\`"
  echo '```'
  eval "$R6"
  echo '```'
  echo ''
  echo '## Calculator frontend exports (pages + components + state hook + pure math)'
  echo "\`\`\`regen: $R7\`\`\`"
  echo '```'
  eval "$R7"
  echo '```'
  echo ''
  echo '## Camera HTTP routes (consumed by the grid)'
  echo "\`\`\`regen: $R8\`\`\`"
  echo '```'
  eval "$R8"
  echo '```'
  echo ''
  echo '## Shared draft/state helper exports (aito + calculator hooks layer)'
  echo "\`\`\`regen: $R9\`\`\`"
  echo '```'
  eval "$R9"
  echo '```'
}
