#!/bin/bash
# Campaign-19 SURFACE generator: the client tracking feature's public contract.
# Regenerate the whole file with:  bash tools/gen_surface_tracking.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS.
set -u
cd "$(dirname "$0")/.." || exit 1

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and (\"track\" in r.path)]" 2>/dev/null'
R2='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/services/aito_tracking.py | sort'
R3='grep -nE "^(def|class|async def) _[a-zA-Z]|^_[A-Z_]+ = |^[A-Z_]+ = " backend/app/services/aito_tracking.py | sed "s/:.*def /: def /; s/ = .*/ =/" | sort -t: -k1 -n | cut -d: -f2- | sed "s/^ *//"'
R4='grep -nE "^(def|async def) _?(track|peer_is_private|release_miss|reset_track|shipping_names|island_labels|external_url)[a-zA-Z_]*\(|^_TRACK_RATE_[A-Z_]+ = |^_track_rate_[a-z_]+: " backend/app/api/routes/aito.py | sed "s/ = .*/ =/; s/: dict.*/:/" | sort -t: -k1 -n | cut -d: -f2- | sed "s/^ *//"'
R5='grep -E "^@router\.(get|post|put|delete)\(\"[^\"]*track[^\"]*\"" backend/app/api/routes/aito.py'
R6='grep -hoE "^class AitoTracking[A-Za-z0-9_]*" backend/app/schemas/aito.py | sort'
R7='./venv/bin/python3 -c "
import json
from backend.app.schemas import aito as s
models = {n: getattr(s, n) for n in dir(s) if n.startswith(\"AitoTracking\")}
print(json.dumps({n: {f: str(x.annotation) for f, x in sorted(m.model_fields.items())} for n, m in sorted(models.items())}, indent=1))" 2>/dev/null'
R8='grep -E "^def _is_tracking_page|^_TRACKING_HTML_HEADERS = |\"/api/v1/aito/track/\"" backend/app/main.py'
R9='grep -oE "^class AitoTrackingView|^    [a-z_]+: Mapped\[[^]]*\]|Index\(\"[^\"]*\"" backend/app/models/aito_tracking_view.py'
R10='grep -E "tracking_token|aito_tracking_views" backend/app/core/database.py | cut -c1-140'
R11='grep -rhoE "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/pages/AitoTrackPage.tsx frontend/src/pages/AitoTrackEntryPage.tsx frontend/src/components/aito/TrackCollapse.tsx frontend/src/components/aito/TrackingCodeInput.tsx frontend/src/components/aito/TrackingInvoice.tsx frontend/src/components/aito/TrackingLanguageSelect.tsx frontend/src/components/aito/TrackingLinkControl.tsx frontend/src/components/aito/TrackingPanel.tsx frontend/src/components/aito/TrackingPayment.tsx frontend/src/components/aito/TrackingPaymentMethods.tsx frontend/src/components/aito/TrackingRail.tsx frontend/src/components/aito/TrackingShopPanel.tsx frontend/src/components/aito/trackingShell.tsx frontend/src/hooks/useTrackingLanguage.ts frontend/src/hooks/useTrackingPanel.ts frontend/src/utils/aitoTracking.ts frontend/src/utils/trackingCode.ts frontend/src/utils/trackingShell.ts | sort'
R12='grep -E "AitoTrack|/t/|/track" frontend/src/App.tsx'
R13='grep -ohE "AitoTracking[A-Za-z0-9_]*|getAitoTracking[A-Za-z]*|regenerateAitoTrackingToken|tracking_configured" frontend/src/api/client.ts | sort -u'
R14='grep -rhoE "aito\.track(ing)?[a-zA-Z0-9_.]*" frontend/src/pages/AitoTrackPage.tsx frontend/src/pages/AitoTrackEntryPage.tsx frontend/src/components/aito/Track*.tsx frontend/src/components/aito/trackingShell.tsx frontend/src/utils/aitoTracking.ts frontend/src/hooks/useTrackingLanguage.ts | sort -u'
R15='grep -oE "^\.(animate-track|code-|track-)[A-Za-z0-9_-]*|^@keyframes (track|code)[A-Za-z0-9_-]*" frontend/src/index.css | sort -u'
R16='grep -oE "^\s+--color-aito-[a-z0-9-]+" frontend/src/index.css | sed "s/^\s*//" | sort -u'
R17='grep -rhoE "track-panel-[a-z]+|data-testid=\"[a-z-]+\"|testId=\"[a-z-]+\"" frontend/src/pages/AitoTrackPage.tsx frontend/src/pages/AitoTrackEntryPage.tsx frontend/src/components/aito/Track*.tsx frontend/src/components/aito/trackingShell.tsx frontend/src/hooks/useTrackingPanel.ts | sort | uniq -c | sed "s/^ *//"'

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-19 public contract: the client tracking page (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_tracking.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a change to something outside this feature`s own'
echo 'internals — a route, a response field, an exported component, a'
echo 'translation key the page reads, a CSS hook the motion is choreographed'
echo 'on, or a tuning constant — and fails the iteration unless the user'
echo 'approved it.'
echo ''

emit 'HTTP routes (paths containing "track")' "$R1"
emit 'Route decorators in routes/aito.py' "$R5"
emit 'aito_tracking.py — public functions' "$R2"
emit 'aito_tracking.py — private helpers and constants (order and names; the module map)' "$R3"
emit 'routes/aito.py — tracking rate limiter and label helpers' "$R4"
emit 'Response models' "$R6"
emit 'AitoTracking* fields' "$R7"
emit 'main.py — tracking page serve' "$R8"
emit 'aito_tracking_views table' "$R9"
emit 'Migrations touching the feature (core/database.py)' "$R10"
emit 'Frontend exports — tracking pages, components, hooks, utils' "$R11"
emit 'App.tsx — tracking routes' "$R12"
emit 'API client — tracking types and methods' "$R13"
emit 'Translation keys the UI reads' "$R14"
emit 'CSS hooks — tracking motion classes and keyframes' "$R15"
emit 'CSS tokens — aito palette' "$R16"
emit 'DOM ids, aria-controls targets and test ids the page binds with' "$R17"
