#!/bin/bash
# Campaign-24 SURFACE generator: the Projects-as-PDM feature's public contract
# (project files/items/revisions, codes, tags, filing + File Manager bridge,
# print traceability, re-slice, Aito task <-> project links).
# Regenerate the whole file with:  bash tools/gen_surface_pdm.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS
# unless the user approved it (BASELINE-CHANGELOG.md entry in the same commit).
# No section pins line numbers (names, routes and order only).
set -u
cd "$(dirname "$0")/.." || exit 1

BE_ROUTES='backend/app/api/routes/projects_pdm.py backend/app/api/routes/project_files.py backend/app/api/routes/aito_project_links.py backend/app/api/routes/projects.py'
BE_SRC="$BE_ROUTES backend/app/services/project_*.py backend/app/services/aito_project_links.py"
BE_SCHEMAS='backend/app/schemas/project.py backend/app/schemas/project_files.py backend/app/schemas/aito_project_links.py'
BE_MODELS='backend/app/models/project.py backend/app/models/project_item.py backend/app/models/project_tag.py backend/app/models/aito_task_delivery.py'
FE_SRC='frontend/src/pages/ProjectDetailPage.tsx frontend/src/pages/ProjectListPage.tsx frontend/src/pages/ProjectsPage.tsx frontend/src/components/projects'

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and (\"project\" in r.path.lower() or r.path.endswith(\"/tasks/{task_id}/files\") or \"deliveries\" in r.path)]" 2>/dev/null'
R2="grep -hE '^@[a-z_]*router\.(get|post|put|patch|delete)\(' $BE_ROUTES | sed 's/, *\$//' | sort"
R3="grep -hE '^(def|class|async def) [a-zA-Z]' $BE_SRC | sed 's/) *->.*/)/; s/:\$//' | sort"
R4="grep -hoE '^class [A-Za-z0-9_]+' $BE_SCHEMAS $BE_MODELS | sort"
R5='./venv/bin/python3 -c "
import json, inspect
from pydantic import BaseModel
import backend.app.schemas.project as a, backend.app.schemas.project_files as b, backend.app.schemas.aito_project_links as c
out = {}
for m in (a, b, c):
    for n, k in sorted(vars(m).items()):
        if inspect.isclass(k) and issubclass(k, BaseModel) and k.__module__ == m.__name__:
            out[n] = {f: str(x.annotation) for f, x in sorted(k.model_fields.items())}
print(json.dumps(out, indent=1, sort_keys=True))" 2>/dev/null'
R6='./venv/bin/python3 -c "import backend.app.main; from sqlalchemy.schema import CreateTable; from sqlalchemy.dialects import sqlite; from backend.app.core.database import Base; [print(str(CreateTable(t).compile(dialect=sqlite.dialect())).strip() + \";\") for n, t in sorted(Base.metadata.tables.items()) if n.startswith(\"project\") or n in (\"aito_task_deliveries\", \"aito_tasks\", \"print_queue\", \"library_files\", \"archives\")]" 2>/dev/null'
R7="grep -hoE 'get_setting\(db, \"[a-z_]+\"|os\.environ\.get\(\"[A-Z_]+\"|settings\.[a-z_]+' $BE_SRC | sort | uniq -c | sed 's/^ *//'"
R8="grep -hoE 'Permission\.[A-Z_]+' $BE_ROUTES | sort | uniq -c | sed 's/^ *//'"
R9='grep -iE "^\s*#\s*Migration:.*(project|revision|deliver|storage_dir|linked_project|P-0|pdm)" backend/app/core/database.py | sed "s/^[[:space:]]*//"'
R10="grep -rhoE --include='*.ts' --include='*.tsx' '^export (default function|default async function|async function|function|const|type|interface|class|enum) [A-Za-z0-9_]+' $FE_SRC | sort | uniq -c | sed 's/^ *//'"
R11='grep -iE "project" frontend/src/App.tsx | sed "s/^[[:space:]]*//"'
R12='grep -oE "^  [a-zA-Z][A-Za-z0-9_]*(:|\\()" frontend/src/api/client.ts | grep -E "[Pp]roject|[Rr]evision|[Rr]eslice|[Ll]egacyMigration|[Ss]uggest" | tr -d ":(" | sort -u'
R13='grep -oE "^export (interface|type) [A-Za-z0-9_]+" frontend/src/api/client.ts | grep -E "Project|Revision|Reslice|LegacyMigration|MoveToProject|DuplicateWarning|RevisionRef|Section|Delivery|OrderProjectLinks|TaskProjectLink" | sort -u'
R14="{ grep -rhoE --include='*.ts' --include='*.tsx' 'projects(Pdm)?\.[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*' $FE_SRC; } | sort -u"
R15="./venv/bin/python3 -c \"import json; from backend.app.core import permissions as p; print(json.dumps({'projects': sorted(x for x in p.ALL_PERMISSIONS if x.startswith('projects:'))}))\" 2>/dev/null"

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-24 public contract: the Projects-as-PDM feature (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_pdm.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a change to something outside the feature`s own'
echo 'internals — a route, a schema field, a table column, an exported symbol,'
echo 'a setting or permission the feature reads, a translation key, an API'
echo 'client method — and fails the iteration unless the user approved it.'
echo ''

emit 'HTTP routes (paths mentioning project, task file drops, deliveries)' "$R1"
emit 'Route decorators (projects_pdm, project_files, aito_project_links, projects)' "$R2"
emit 'Backend public callables (routes + services)' "$R3"
emit 'Pydantic schema + ORM model class names' "$R4"
emit 'Pydantic schema fields (project, project_files, aito_project_links)' "$R5"
emit 'Tables the feature owns or extends — DDL' "$R6"
emit 'Settings keys, env vars and config attributes read by the backend' "$R7"
emit 'Permissions guarding the routes (count per permission)' "$R8"
emit 'Migrations touching the feature (core/database.py comments)' "$R9"
emit 'Frontend exported symbols (count per symbol name)' "$R10"
emit 'App.tsx — project routes' "$R11"
emit 'API client — project / revision / reslice / migration methods' "$R12"
emit 'API client — exported project types' "$R13"
emit 'Translation keys the project UI reads (projects.* / projectsPdm.* literals)' "$R14"
emit 'projects:* permissions' "$R15"
