#!/bin/bash
# Campaign-18 SURFACE generator: the Aito statistics feature's public contract.
# Regenerate the whole file with:  bash tools/gen_surface_stats.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS.
set -u
cd "$(dirname "$0")/.." || exit 1

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/aito/stats\" in r.path]" 2>/dev/null'
R2='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/services/aito_stats.py | sort'
R3='grep -nE "^(def|class|async def) _[a-zA-Z]" backend/app/services/aito_stats.py | sed "s/:.*def /: def /" | sort -t: -k1 -n'
R4='grep -hoE "^class AitoStats[A-Za-z0-9_]*" backend/app/schemas/aito.py | sort'
R5='./venv/bin/python3 -c "
import json
from backend.app.schemas.aito import AitoStatsResponse
f = AitoStatsResponse.model_fields
print(json.dumps({n: str(x.annotation) for n, x in sorted(f.items())}, indent=1))" 2>/dev/null'
R6='grep -rhoE "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/components/aito/stats frontend/src/components/aito/StatsView.tsx | sort'
R7='grep -hoE "^export (const|function|type|interface) [A-Za-z0-9_]+" frontend/src/components/stats/timeframe.ts frontend/src/components/stats/TimeframeSelector.tsx | sort'
R8='grep -ohE "AitoStats[A-Za-z0-9_]*|getAitoStats" frontend/src/api/client.ts | sort -u'
R9='grep -rhoE "aito\.stats\.[a-zA-Z0-9_.]+" frontend/src/components/aito frontend/src/pages/AitoPage.tsx | sort -u'
R10='grep -hoE "^(export )?(const|let) [A-Z_]+ =|^const [A-Z_]+ =" frontend/src/components/aito/stats/*.tsx frontend/src/components/aito/stats/*.ts | sort -u'

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-18 public contract: the Aito statistics feature (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_stats.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a change to something outside this feature`s own'
echo 'internals — a route, a response field, an exported component, a'
echo 'translation key the UI reads, or a tuning constant the screens are'
echo 'calibrated against — and fails the iteration unless the user approved it.'
echo ''

emit 'HTTP routes' "$R1"
emit 'aito_stats.py — public functions' "$R2"
emit 'aito_stats.py — private helpers (order and names; the module map)' "$R3"
emit 'Response models' "$R4"
emit 'AitoStatsResponse fields' "$R5"
emit 'Frontend exports — statistics view' "$R6"
emit 'Frontend exports — timeframe (shared with the Fenrir stats page)' "$R7"
emit 'API client — statistics types' "$R8"
emit 'Translation keys the UI reads' "$R9"
emit 'Tuning constants' "$R10"
