#!/bin/bash
# Campaign-22 SURFACE generator: the public contract of the camera wall
# (grid-stream hub + fan-out service + frontend camera grid and stream hooks)
# and of the Aito card hover dwell (CardView + hoverWarmth).
# Regenerate the whole file with:  bash tools/gen_surface_c22.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS
# unless the user approved it (BASELINE-CHANGELOG.md entry in the same commit).
# No section pins line numbers (names, routes and order only).
set -u
cd "$(dirname "$0")/.." || exit 1

BE_SRC='backend/app/api/routes/camera.py backend/app/services/camera_fanout.py'
FE_SRC='frontend/src/components/CameraGrid.tsx frontend/src/components/cameraGrid frontend/src/components/cameraGridLayout.ts frontend/src/components/cameraDefaults.ts frontend/src/hooks/useGridStream.ts frontend/src/hooks/useGridReconnect.ts frontend/src/hooks/useCombinedGridStats.ts frontend/src/hooks/useWebRTCStream.ts frontend/src/hooks/useMjpegStream.ts frontend/src/hooks/useStreamReconnect.ts frontend/src/hooks/useCameraStreamToken.ts frontend/src/utils/streamBuffer.ts frontend/src/utils/streamConstants.ts frontend/src/workers/cameraGridDecoder.worker.ts frontend/src/components/aito/CardView.tsx frontend/src/components/aito/hoverWarmth.ts'

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods) if hasattr(r, \"methods\") else \"[WS]\") for r in sorted(app.routes, key=lambda r: r.path) if \"/camera\" in r.path]" 2>/dev/null'
R2='grep -hE "^@router\.(get|post|put|patch|delete|websocket)\(" backend/app/api/routes/camera.py | sed "s/, *$//" | sort'
R3="grep -hE '^(def|class|async def) [a-zA-Z]|^    (async )?def [a-zA-Z]' $BE_SRC | sed 's/) *->.*/)/; s/:\$//' | sort"
R4='./venv/bin/python3 -c "
import json, inspect
from pydantic import BaseModel
import backend.app.api.routes.camera as m
out = {}
for n, c in sorted(vars(m).items()):
    if inspect.isclass(c) and issubclass(c, BaseModel) and c.__module__ == m.__name__:
        out[n] = {f: str(x.annotation) for f, x in sorted(c.model_fields.items())}
print(json.dumps(out, indent=1, sort_keys=True))" 2>/dev/null'
R5='for f in camera_grid_stream camera_hub_status create_stream_token camera_stream stop_camera_stream; do awk -v f="$f" "\$0 ~ \"^async def \" f \"\\\\(\" {p=1} p {print} p && /^\\)/ {exit}" backend/app/api/routes/camera.py | sed "s/^[[:space:]]*//"; done'
R6="grep -hoE 'settings_map\.get\(\"[a-z_]+\"\)|\"camera_[a-z_]+\"|settings\.[a-z_]+|os\.environ\.get\(\"[A-Z_]+\"|env_get\(\"[A-Z_]+\"' $BE_SRC | sort -u"
R7='grep -hoE "RequirePermissionIfAuthEnabled\([^)]*\)|Permission\.[A-Z_]+" backend/app/api/routes/camera.py | sort | uniq -c | sed "s/^ *//"'
R8="grep -rhoE --include='*.ts' --include='*.tsx' '^export (default function|default async function|async function|function|const|type|interface|class|enum) [A-Za-z0-9_]+' $FE_SRC | sort | uniq -c | sed 's/^ *//'"
R9="grep -rhoE --include='*.ts' --include='*.tsx' \"[^A-Za-z]t\\(['\\\"\\\`][a-zA-Z0-9_.]+['\\\"\\\`]\" $FE_SRC | sed \"s/^.t(//\" | tr -d \"'\\\"\\\`\" | sort -u"
R10='grep -oE "^  [a-zA-Z][A-Za-z0-9_]*(:|\\()" frontend/src/api/client.ts | grep -iE "camera|grid|stream|webrtc|mse|token" | tr -d ":(" | sort -u'
R11="grep -rhoE --include='*.ts' --include='*.tsx' \"localStorage\\.(getItem|setItem|removeItem)\\(['\\\"][A-Za-z0-9_.-]+['\\\"]\" $FE_SRC frontend/src/pages/PrintersPage.tsx | sort -u"
R12='{ grep -oE "pageView === '"'"'[a-z]+'"'"'" frontend/src/pages/PrintersPage.tsx | sort -u; grep -oE "^function CamWallClock" frontend/src/pages/PrintersPage.tsx; awk "/<CameraGrid\$/ {p=1} p {print} p && /\\/>/ {exit}" frontend/src/pages/PrintersPage.tsx | grep -oE "^ +[a-zA-Z]+=" | tr -d " =" | sort; }'
R13="grep -rhoE --include='*.ts' \"type: '[a-zA-Z-]+'\" frontend/src/workers/cameraGridDecoder.worker.ts frontend/src/hooks/useGridStream.ts | sort | uniq -c | sed 's/^ *//'"
R14='grep -oE "grid-stream[^\"'"'"'\`]*|/camera/[a-z-]+" frontend/src/hooks/useGridStream.ts frontend/src/hooks/useWebRTCStream.ts frontend/src/hooks/useMjpegStream.ts frontend/src/hooks/useCameraStreamToken.ts frontend/src/api/client.ts | sort -u'

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-22 public contract: camera wall + card hover dwell (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_c22.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a change to something outside the feature`s own'
echo 'internals — a route, a request/response model, a route signature, an'
echo 'exported symbol, a setting or permission the feature reads, a translation'
echo 'key, an API client method, a localStorage key, a worker message type —'
echo 'and fails the iteration unless the user approved it.'
echo ''

emit 'HTTP + WebSocket routes (paths containing /camera)' "$R1"
emit 'Route decorators (routes/camera.py)' "$R2"
emit 'Backend public callables and methods (camera.py + camera_fanout.py)' "$R3"
emit 'Pydantic models defined in routes/camera.py' "$R4"
emit 'Route signatures — grid stream, hub status, stream token, stream, stop' "$R5"
emit 'Settings keys and env vars read by the camera backend' "$R6"
emit 'Permissions guarding camera routes (count per permission)' "$R7"
emit 'Frontend exported symbols (count per symbol name)' "$R8"
emit 'Translation keys the camera wall + CardView read (t() literals)' "$R9"
emit 'API client — camera / grid / stream / token methods' "$R10"
emit 'localStorage keys (scope files + PrintersPage)' "$R11"
emit 'PrintersPage camera-wall wiring (page views, wall clock, CameraGrid props)' "$R12"
emit 'Decoder worker message types' "$R13"
emit 'Camera endpoints the frontend hooks call' "$R14"
