#!/bin/bash
# Campaign-8 SURFACE generator (campaign 6's, + hooks/useSettledValue.ts in R8): the Calculator x Zoho feature's public contract.
# Regenerate the whole file with:  bash tools/gen_surface_calc.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS.
#
# Globs are written RECURSIVELY (**) where a subdirectory could appear:
# campaign 4 discovered gen_surface.sh's non-recursive `components/aito/*.tsx`
# had made two whole subdirectories invisible to the frozen contract.
set -u
cd "$(dirname "$0")/.." || exit 1

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/calculator\" in r.path]" 2>/dev/null'
R2='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/api/routes/calculator.py backend/app/services/zoho_filaments.py backend/app/services/calculator_insights.py | sort'
R3='grep -hoE "^class [A-Za-z0-9_]+" backend/app/schemas/calculator.py backend/app/models/calculator.py | sort'
R4='grep -hoE "^_?[A-Z][A-Z0-9_]+ =" backend/app/api/routes/calculator.py backend/app/services/zoho_filaments.py backend/app/services/calculator_insights.py | tr -d " =" | sort'
R5='grep -hoE "settings\.[a-z_]+" backend/app/api/routes/calculator.py backend/app/services/zoho_filaments.py backend/app/services/calculator_insights.py | sort -u'
R6='grep -hoE "RequirePermissionIfAuthEnabled\(Permission\.[A-Z_]+\)" backend/app/api/routes/calculator.py | sort | uniq -c | sed "s/^ *//"'
R7='./venv/bin/python3 -c "import backend.app.main; from sqlalchemy.schema import CreateTable; from sqlalchemy.dialects import sqlite; from backend.app.core.database import Base; [print(str(CreateTable(t).compile(dialect=sqlite.dialect())).strip() + \";\") for n, t in sorted(Base.metadata.tables.items()) if n.startswith(\"calculator_\")]" 2>/dev/null'
R8='grep -hoE "^export (const|function|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/utils/calculatorInsights.ts frontend/src/utils/quoteSummary.ts frontend/src/utils/pricing.ts frontend/src/hooks/useCalculatorState.ts frontend/src/hooks/useSettledValue.ts | sort'
R9='grep -rhoE --include="*.ts" --include="*.tsx" "^export (default function|function|const|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/components/calculator frontend/src/components/CalculatorSettingsPanels.tsx frontend/src/pages/CalculatorPage.tsx frontend/src/pages/CalculatorQuotePage.tsx | sort | uniq -c | sed "s/^ *//"'
R10='grep -oE "^  [a-zA-Z][A-Za-z0-9_]*(:|\()" frontend/src/api/client.ts | grep -iE "calculator|zohofilament" | tr -d ":(" | sort -u'

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-6 public contract: the Calculator x Zoho feature (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_calc.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a contract change and fails the iteration.'
echo ''
emit 'Calculator HTTP routes (path + methods)'              "$R1"
emit 'Calculator backend callables (public and private)'    "$R2"
emit 'Calculator Pydantic schemas + ORM models'             "$R3"
emit 'Calculator backend module constants'                  "$R4"
emit 'Settings keys read by the calculator backend'         "$R5"
emit 'Permission gates on calculator routes'                "$R6"
emit 'calculator_* table DDL'                               "$R7"
emit 'Calculator frontend exported symbols (utils + hooks)' "$R8"
emit 'Calculator component exports (count per symbol name)' "$R9"
emit 'Calculator API client methods'                        "$R10"
