#!/bin/bash
# Campaign-7 SURFACE generator: the filament-profiles Zoho price sync contract.
# Regenerate the whole file with:  bash tools/gen_surface_fp.sh > SURFACE.md
# Every section is produced by the `regen:` command printed above it, so the
# file is byte-replayable. ANY diff = a surface change = the iteration FAILS.
set -u
cd "$(dirname "$0")/.." || exit 1

R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/filament-profiles\" in r.path]" 2>/dev/null'
R2='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/api/routes/filament_profiles.py backend/app/services/filament_profile_pricing.py backend/app/services/zoho_filaments.py | sort'
R3='grep -hoE "^class [A-Za-z0-9_]+" backend/app/schemas/filament_profile.py backend/app/models/filament_profile.py | sort'
R4='grep -hoE "^_?[A-Z][A-Z0-9_]+ =" backend/app/api/routes/filament_profiles.py backend/app/services/filament_profile_pricing.py backend/app/services/zoho_filaments.py | tr -d " =" | sort'
R5='grep -hoE "RequirePermissionIfAuthEnabled\(Permission\.[A-Z_]+\)" backend/app/api/routes/filament_profiles.py | sort | uniq -c | sed "s/^ *//"'
R6='./venv/bin/python3 -c "import json,backend.app.main as m; s=m.app.openapi(); [print(k, json.dumps(v, sort_keys=True)) for k,v in sorted(s[\"components\"][\"schemas\"].items()) if \"FilamentPreset\" in k or \"BaseFilamentPreset\" in k or \"BambuSync\" in k or \"BaseContent\" in k]" 2>/dev/null'
R7='./venv/bin/python3 -c "import backend.app.main; from sqlalchemy.schema import CreateTable; from sqlalchemy.dialects import sqlite; from backend.app.core.database import Base; [print(str(CreateTable(t).compile(dialect=sqlite.dialect())).strip() + \";\") for n, t in sorted(Base.metadata.tables.items()) if \"filament_preset\" in n or n.startswith(\"filament_profile\")]" 2>/dev/null'
R8='grep -oE "^export (default function|function|const|type|interface) [A-Za-z0-9_]+" frontend/src/pages/FilamentProfilesPage.tsx | sort'
R9='grep -oE "^  [a-zA-Z][A-Za-z0-9_]*(:|\()" frontend/src/api/client.ts | grep -iE "filamentpreset|filamentprofile|filament-profile" | tr -d ":(" | sort -u'
R10='grep -hoE "^export (type|interface) (FilamentPreset|BaseFilamentPreset)[A-Za-z0-9_]*" frontend/src/api/client.ts | sort'
R11='bash tools/fp_i18n_keys.sh'

emit() { # emit <heading> <cmd>
  local heading="$1" cmd="$2"
  echo "## $heading"
  echo "\`\`\`regen: $cmd\`\`\`"
  echo '```'
  eval "$cmd"
  echo '```'
  echo ''
}

echo '# SURFACE.md — campaign-7 public contract: the filament-profiles Zoho price sync (frozen at setup)'
echo ''
echo 'Generated by `bash tools/gen_surface_fp.sh > SURFACE.md`. Each section is'
echo 'replayable by the `regen:` command shown above it. Any diff against the'
echo 'committed copy is a contract change and fails the iteration.'
echo ''
emit 'filament-profiles HTTP routes (path + methods)'        "$R1"
emit 'Backend callables (public and private)'                "$R2"
emit 'Pydantic schemas + ORM models (class names)'           "$R3"
emit 'Backend module constants'                              "$R4"
emit 'Permission gates on filament-profiles routes'          "$R5"
emit 'OpenAPI schema bodies for the filament-preset DTOs'    "$R6"
emit 'filament preset table DDL'                             "$R7"
emit 'FilamentProfilesPage exported symbols'                 "$R8"
emit 'API client methods for filament profiles'              "$R9"
emit 'API client filament-preset types'                      "$R10"
emit 'i18n keys the page reads'                              "$R11"
