set -u
cd /Users/paultheis/Documents/Code/bambuddy-refactor
R1='./venv/bin/python3 -c "from backend.app.main import app; [print(r.path, sorted(r.methods)) for r in sorted(app.routes, key=lambda r: r.path) if hasattr(r, \"methods\") and \"/aito\" in r.path]" 2>/dev/null'
R2='grep -hoE "^export (const|function|type|interface|class|enum) [A-Za-z0-9_]+" frontend/src/utils/aito*.ts frontend/src/hooks/useAito*.ts | sort'
R3='grep -hoE "^export (default function|function|const|type|interface) [A-Za-z0-9_]+" frontend/src/components/aito/*.tsx frontend/src/components/aito/*.ts frontend/src/pages/AitoPage.tsx | sort | uniq -c | sed "s/^ *//"'
R4='grep -hE "^(def|class|async def) [a-zA-Z]" backend/app/services/aito_*.py backend/app/api/routes/aito.py | grep -v "^def _\|^async def _" | sort'
R5='grep -hoE "settings\.[a-z_]+" backend/app/api/routes/aito.py backend/app/services/aito_*.py | sort -u'

{
  echo '# SURFACE.md — Aito feature public contract (frozen at setup)'
  echo ''
  echo 'Every section below is generated by the `regen:` command shown above it and is'
  echo 'byte-replayable by re-running that command. Regenerate all of them with'
  echo '`bash tools/gen_surface.sh > SURFACE.md`. ANY diff against this file is a'
  echo 'surface change and fails the iteration.'
  echo ''
  echo '## HTTP routes'
  echo "\`\`\`regen: $R1\`\`\`"
  echo '```'
  eval "$R1"
  echo '```'
  echo ''
  echo '## Frontend exported symbols (utils + hooks)'
  echo "\`\`\`regen: $R2\`\`\`"
  echo '```'
  eval "$R2"
  echo '```'
  echo ''
  echo '## Frontend component exports (name + count per kind)'
  echo "\`\`\`regen: $R3\`\`\`"
  echo '```'
  eval "$R3"
  echo '```'
  echo ''
  echo '## Backend service/module public functions'
  echo "\`\`\`regen: $R4\`\`\`"
  echo '```'
  eval "$R4"
  echo '```'
  echo ''
  echo '## Settings/env keys referenced by aito modules'
  echo "\`\`\`regen: $R5\`\`\`"
  echo '```'
  eval "$R5"
  echo '```'
}
